### ISSUE TITLE
[Feat] Performance CreatedAt 추가

### ISSUE THREAD

**Issue by UIMAPH** [qedcorp/MacC-Team6-QED#117]
# Description
 Performance CreatedAt 추가,
 Firestore에도 추가
 MainView에 최근 Performance에 해당내용으로 정렬

# Tasks
- [x] Performance CreatedAt 추가
- [x] Firestore DTO에 CreatedAt 추가
- [x] MainView에 RecentPerformances 최신순 정렬
