### ISSUE TITLE
performanceSetting 오류 해결

### ISSUE THREAD

**Issue by OLING99** [qedcorp/MacC-Team6-QED#163]
# Description
performanceSetting 오류 해결

# Tasks
- [ ] textfield 바로 focus 안되는거 잡기
- [ ] 노래 검색 버튼 넣기
- [ ] 인원선택 slider 오류
