### ISSUE TITLE
[Feat] 최종 개발팀 QA

### ISSUE THREAD

**Issue by byoth** [qedcorp/MacC-Team6-QED#170]
# Tasks
- [x] PresetContainer 초기화되는 버그
- [ ] 인물지정 오브젝트 크기 수정
- [x] 세부동선 한 칸 씩 밀리는 이슈
- [x] 세부동선 이전 오브젝트 디자인 이슈
