### ISSUE TITLE
[Hotfix] 1.1.1

### ISSUE THREAD

**Issue by byoth** [qedcorp/MacC-Team6-QED#216]
# Tasks
- [ ] GIF 용량 최적화
- [ ] CardView spacing 제거 (이미지 로딩, 버튼 클릭 효과에서 조잡한 사이드이펙트 생겼음)
- [ ] PerformanceSettingView padding 조정
