### ISSUE TITLE
[Feat] kakao 공유하기 UI 수정

### ISSUE THREAD

**Issue by Dunkkkk** [qedcorp/MacC-Team6-QED#227]
# Description
 kakao 공유하기 UI 수정

# Tasks
- [x] button size fix
- [x] font size fix
- [x] alert size fix
